phrases = {
    'en' : {
        'volounter': 'Volounter',
        'needy': 'Needy',
        'home': 'Home',
        'food': 'Food',
        'medical care': 'Medical care',
        'transport': 'Transport',
        'kids products': 'Kids products',
        'products for pets': 'Products for pets',
        'clothes': 'Clothes',
        'essentials': 'Essentials',
        'psychological help': 'Psychological help',
        'donate': 'Donate',
        'other': 'Pther',
        'back': 'Back'
    },
    'ru' : {
        'volounter': 'Волонтёр',
        'needy': 'Нуждающийся в помощи',
        'home': 'Жилье',
        'food': 'Питание',
        'medical care': 'Медицинская помощь',
        'transport': 'Транспорт',
        'kids products': 'Детские товары',
        'products for pets': 'Товары для животных',
        'clothes': 'Одежда',
        'essentials': 'Вещи первой необходимости',
        'psychological help': 'Психологическая помощь',
        'donate': 'Сделать пожертвывание',
        'other': 'Другое',
        'back': 'Назад',
    },
    'uk' : {
        'volounter': 'Волонтер',
        'needy': 'Потребуючий допомоги',
        'home': 'Житло',
        'food': 'Харчування',
        'medical care': 'Медична допомога',
        'transport': 'Транспорт',
        'kids products': 'Дитячі товари',
        'products for pets': 'Товари для тварин',
        'clothes': 'Одежа',
        'essentials': 'Речі першої необхідності',
        'psychological help': 'Психологічна допомога',
        'donate': 'Зробити пожертву',
        'other': 'Інше',
        'back': 'Назад',
    },
}