phrases = {
    'en' : {
        'volounter': 'Volounter',
        'needy': 'Needy',
        'home': 'Home',
        'food': 'Food',
        'medical care': 'Medical care',
        'transport': 'Transport',
        'kids products': 'Kids products',
        'products for pets': 'Products for pets',
        'clothes': 'Clothes',
        'essentials': 'Essentials',
        'psychological help': 'Psychological help',
        'donate': 'Donate',
        'other': 'Other',
        'back': 'Back',
        'after_type': 'Choose what you want to do',
        'make post': 'Make post',
        'show posts': 'Show request',
        'edit post': 'Edit post',
        'postig sites': 'Sites for finding or placing housing',
        'psysites': 'Other resources for psychological help',
        'transportsites': 'Sites for finding transport',
        'liqpay':'Fund for helping the needy',
        'army':'Army Support Fund',
        'runner':'Refugee Support Fund',
        
    },
    'ru' : {
        'volounter': 'Волонтёр',
        'needy': 'Нуждающийся в помощи',
        'home': 'Жилье',
        'food': 'Питание',
        'medical care': 'Медицинская помощь',
        'transport': 'Транспорт',
        'kids products': 'Детские товары',
        'products for pets': 'Товары для животных',
        'clothes': 'Одежда',
        'essentials': 'Вещи первой необходимости',
        'psychological help': 'Психологическая помощь',
        'donate': 'Сделать пожертвывание',
        'other': 'Другое',
        'back': 'Назад',
        'after_type': 'Выберите что вы хотите сделать',
        'make post': 'Создать пост',
        'show posts': 'Показаь запросы',
        'edit post': 'Редактировать мои посты',
        'postig sites': 'Сайты для поиска или размещения жилья',
        'psysites': 'Другие ресурсы для психологической помощи',
        'transportsites': 'Сайты для поиска транспорта',
        'liqpay':'Фонд для помощи нуждающимся',
        'army':'Фонд для поддержки армии',
        'runner':'Фонд поддержки беженцев',
        
    },
    'uk' : {
        'volounter': 'Волонтер',
        'needy': 'Потребуючий допомоги',
        'home': 'Житло',
        'food': 'Харчування',
        'medical care': 'Медична допомога',
        'transport': 'Транспорт',
        'kids products': 'Дитячі товари',
        'products for pets': 'Товари для тварин',
        'clothes': 'Одежа',
        'essentials': 'Речі першої необхідності',
        'psychological help': 'Психологічна допомога',
        'donate': 'Зробити пожертву',
        'other': 'Інше',
        'back': 'Назад',
        'after_type': 'Виберіть, що ви хочете зробити',
        'make post': 'Створити пост',
        'show posts': 'Переглянути запити',
        'edit post': 'Редагувати мої пости',
        'postig sites': 'Сайти для пошуку або розміщення житла',
        'psysites': 'Інші ресурси для отримання психологічної допомоги',
        'transportsites': 'Сайти для пошуку транспорту',
        'liqpay':'Фонд для допомоги потребуючим',
        'army':'Фонд для підтримки армії',
        'runner':'Фонд для підтримки біженців',
        
    },
}
buttons_neddy = {
    'en':{
        'make post': 'Make request',
        'show posts': 'Show posts',
        'edit post': 'Edit request',
    },
    'ru':{
        'make post': 'Создать запрос',
        'show posts': 'Показать посты',
        'edit post': 'Редактировать запрос',
    },
    'uk':{
        'make post': 'Створити запит',
        'show posts': 'Показати пости',
        'edit post': 'Редагувати запит',
    }
}
regions ={
    'en' : (
        'Odesa',
        'Cherkasy',
        'Chernihiv',
        'Chernivtsi',
        'Dnipropetrovsk',
        'Donetsk',
        'Ivano-Frankivsk',
        'Kharkiv',
        'Kherson',
        'Khmelnytsk',
        'Kirovohrad',
        'Kyiv',
        'Luhansk',
        'Lviv',
        'Mykolaiv',
        'Poltava',
        'Rivne',
        'Sumy',
        'Ternopil',
        'Vinnytsia',
        'Volyn',
        'Zakarpattia ',
        'Zaporizhzhia',
        'Zhytomyr',
    ),
    'ru' : (
        'Одесса',
        'Днепропетровск',
        'Чернигов',
        'Харьков',
        'Житомер',
        'Полтава',
        'Херсон',
        'Киев',
        'Запорожье',
        'Луганск',
        'Донецк',
        'Винница',
        'Кировоград',
        'Николаев',
        'Суммы',
        'Львов',
        'Черкасы',
        'Хмельницк',
        'Волынь',
        'Ровенская',
        'Ивано-Франковск',
        'Тернополь ',
        'Закарпатье',
        'Черновцы',
    ),
    'uk' : (
        'Одеса',
        'Дніпропетровськ',
        'Чернігів',
        'Харьків',
        'Житомир',
        'Полтава',
        'Херсон',
        'Київ',
        'Запоріжжя',
        'Луганськ',
        'Донецьк',
        'Вінниця',
        'Кіровоград',
        'Миколаїв',
        'Суми',
        'Львів',
        'Черкаси',
        'Хмельницьк',
        'Волинь',
        'Рівне',
        'Івано-Франківськ',
        'Тернопіль ',
        'Закарпаття',
        'Чернівці',
    )
}
boll_answer = {
    'en' : (
        'Yes',
        'No',
    ),
    'ru' : (
        'Да',
        'Нет',
    ),
    'uk' : (
        'Так',
        'НЫ',
    )
}
make_post = {
   'en' : (
       'Choose region',
        'Write how many beds you can choose',
        'You entered the wrong quantity',
        'For the period of stay in which you can allocate',
        'Do you accept animals?',
        'Send Photo',
        'Send additional comment',
        'Thank you, your post has been accepted',
        'What can you provide',
        'Write the type of clothing',
        'Write the size of the clothes',
        'How many beds do you need',
        'How long do you need housing',
        'Animals will be with you',
        'What do you need',
   ),
   'ru' : (
        'Выберите регион',
        'Напишите сколько спальных мест вы можете предоставить',
        'Вы ввели неправильное количество',
        'Напишите промежуток времени в которое вы можете предоставить жилье',
        'Принимаете ли вы животных?',
        'Отправьте Фото',
        'Отправьте дополнительний коментарий',
        'Спасибо, ваш пост принят',
        'Что вы можете предоставить',
        'Напишите тип одежды',
        'Напишите размер одежды',
        'В скольки спальных местах вы нуждаетесь',
        'В какой промежуток ввремени вы нуждаетесь в жилье',
        'С вами будут животные',
        'В чем вы нуждаетесь',
    ),
   'uk':(
        'Виберіть регіон',
        'Напишіть, скільки спальних місць ви можете надати',
        'Ви ввели неправильну кількість',
        'Який термін проживання, в якому ви надаєте',
        'Чи приймаєте ви тварин?',
        'Надіслати  Фото',
        'Надіслати додатковий коментар',
        'Дякую, ваш пост прийнято',
        'Що ви можете надати',
        'Напишіть тип одягу',
        'Напишіть розмір одягу',
        'Скільки спальних місць ви потребуєте',
        'У який проміжок часу ви потребуєте житла',
        'З вами будуть тварини',
        'Чого ви потребуєте',
    ) 
}
showPost = {
    'en' : (
        'Amount of bed: ',
        'Time to stay accommodatio: ',
        'Pets: ',
        'Comment: ',
        'Confirm',
        'Reject',
    ),
    'ru' : (
        'Количество спальных мет: ',
        'Время возможного проживания:',
        'Животные: ',
        'Коментарий: ',
        'Принять',
        'Отклонить',
    ),
    'uk' : (
        'Кількість спальних місць: ',
        'Час можливого проживання: ',
        'Тварини: ',
        'Коментар: ',
        'Прийняти',
        'Відхилити:',
    ),
}
editPost = {
    'en' : (
        'Enter id of post',
        'Select action',
        'Post has been deleted'
    ),
    'ru' : (
        'Введите id поста',
        'Выберите что хотите сделать',
        'Публикация был удалена'
    ),
    'uk' : (
        'Введіть id поста',
        'виберіть що хочете зробити',
        'Публікація була видалена'
    ),
}